// Code generated by goderive DO NOT EDIT.

package geom

// deriveCloneBounds returns a clone of the src parameter.
func deriveCloneBounds(src *Bounds) *Bounds { _ = "STUB: not implemented"; return nil }

// deriveCloneCoord returns a clone of the src parameter.
func deriveCloneCoord(src Coord) Coord { _ = "STUB: not implemented"; return *new(Coord) }

// deriveCloneLinearRing returns a clone of the src parameter.
func deriveCloneLinearRing(src *LinearRing) *LinearRing { _ = "STUB: not implemented"; return nil }

// deriveCloneLineString returns a clone of the src parameter.
func deriveCloneLineString(src *LineString) *LineString { _ = "STUB: not implemented"; return nil }

// deriveCloneMultiLineString returns a clone of the src parameter.
func deriveCloneMultiLineString(src *MultiLineString) *MultiLineString {
	_ = "STUB: not implemented"
	return nil
}

// deriveCloneMultiPoint returns a clone of the src parameter.
func deriveCloneMultiPoint(src *MultiPoint) *MultiPoint { _ = "STUB: not implemented"; return nil }

// deriveCloneMultiPolygon returns a clone of the src parameter.
func deriveCloneMultiPolygon(src *MultiPolygon) *MultiPolygon {
	_ = "STUB: not implemented"
	return nil
}

// deriveClonePoint returns a clone of the src parameter.
func deriveClonePoint(src *Point) *Point { _ = "STUB: not implemented"; return nil }

// deriveClonePolygon returns a clone of the src parameter.
func deriveClonePolygon(src *Polygon) *Polygon { _ = "STUB: not implemented"; return nil }

// deriveDeepCopy recursively copies the contents of src into dst.
func deriveDeepCopy(dst, src *Bounds) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_ recursively copies the contents of src into dst.
func deriveDeepCopy_(dst, src Coord) {
	_ = "STUB: not implemented"

	// deriveDeepCopy_1 recursively copies the contents of src into dst.
	return
}

func deriveDeepCopy_1(dst, src *LinearRing) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_2 recursively copies the contents of src into dst.
func deriveDeepCopy_2(dst, src *LineString) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_3 recursively copies the contents of src into dst.
func deriveDeepCopy_3(dst, src *MultiLineString) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_4 recursively copies the contents of src into dst.
func deriveDeepCopy_4(dst, src *MultiPoint) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_5 recursively copies the contents of src into dst.
func deriveDeepCopy_5(dst, src *MultiPolygon) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_6 recursively copies the contents of src into dst.
func deriveDeepCopy_6(dst, src *Point) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_7 recursively copies the contents of src into dst.
func deriveDeepCopy_7(dst, src *Polygon) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_8 recursively copies the contents of src into dst.
func deriveDeepCopy_8(dst, src *geom1) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_9 recursively copies the contents of src into dst.
func deriveDeepCopy_9(dst, src *geom2) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_10 recursively copies the contents of src into dst.
func deriveDeepCopy_10(dst, src *geom3) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_11 recursively copies the contents of src into dst.
func deriveDeepCopy_11(dst, src *geom0) { _ = "STUB: not implemented"; return }

// deriveDeepCopy_12 recursively copies the contents of src into dst.
func deriveDeepCopy_12(dst, src [][]int) { _ = "STUB: not implemented"; return }
