// Code generated by goyacc -l -o wkt.gen.go -p wkt wkt.y. DO NOT EDIT.

package wkt

import (
	"github.com/twpayne/go-geom"
)

type wktSymType struct {
	yys               int
	str               string
	geom              geom.T
	coord             float64
	coordList         []float64
	flatRepr          geomFlatCoordsRepr
	multiPolyFlatRepr multiPolygonFlatCoordsRepr
	geomList          []geom.T
	geomCollect       *geom.GeometryCollection
}

const (
	POINT                = 57346
	POINTM               = 57347
	POINTZ               = 57348
	POINTZM              = 57349
	LINESTRING           = 57350
	LINESTRINGM          = 57351
	LINESTRINGZ          = 57352
	LINESTRINGZM         = 57353
	POLYGON              = 57354
	POLYGONM             = 57355
	POLYGONZ             = 57356
	POLYGONZM            = 57357
	MULTIPOINT           = 57358
	MULTIPOINTM          = 57359
	MULTIPOINTZ          = 57360
	MULTIPOINTZM         = 57361
	MULTILINESTRING      = 57362
	MULTILINESTRINGM     = 57363
	MULTILINESTRINGZ     = 57364
	MULTILINESTRINGZM    = 57365
	MULTIPOLYGON         = 57366
	MULTIPOLYGONM        = 57367
	MULTIPOLYGONZ        = 57368
	MULTIPOLYGONZM       = 57369
	GEOMETRYCOLLECTION   = 57370
	GEOMETRYCOLLECTIONM  = 57371
	GEOMETRYCOLLECTIONZ  = 57372
	GEOMETRYCOLLECTIONZM = 57373
	EMPTY                = 57374
	NUM                  = 57375
)

var wktToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"POINT",
	"POINTM",
	"POINTZ",
	"POINTZM",
	"LINESTRING",
	"LINESTRINGM",
	"LINESTRINGZ",
	"LINESTRINGZM",
	"POLYGON",
	"POLYGONM",
	"POLYGONZ",
	"POLYGONZM",
	"MULTIPOINT",
	"MULTIPOINTM",
	"MULTIPOINTZ",
	"MULTIPOINTZM",
	"MULTILINESTRING",
	"MULTILINESTRINGM",
	"MULTILINESTRINGZ",
	"MULTILINESTRINGZM",
	"MULTIPOLYGON",
	"MULTIPOLYGONM",
	"MULTIPOLYGONZ",
	"MULTIPOLYGONZM",
	"GEOMETRYCOLLECTION",
	"GEOMETRYCOLLECTIONM",
	"GEOMETRYCOLLECTIONZ",
	"GEOMETRYCOLLECTIONZM",
	"EMPTY",
	"NUM",
	"'('",
	"')'",
	"','",
}

var wktStatenames = [...]string{}

const (
	wktEofCode          = 1
	wktErrCode          = 2
	wktInitialStackSize = 16
)

var wktExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const wktPrivate = 57344

const wktLast = 218

var wktAct = [...]uint8{
	66, 2, 116, 126, 131, 106, 65, 111, 128, 121,
	60, 57, 137, 118, 155, 156, 61, 70, 58, 101,
	75, 114, 81, 63, 87, 69, 63, 64, 104, 63,
	61, 63, 90, 63, 62, 63, 107, 68, 63, 61,
	72, 84, 77, 61, 83, 78, 89, 108, 59, 94,
	58, 67, 153, 154, 71, 92, 74, 97, 80, 61,
	86, 151, 152, 93, 149, 150, 147, 148, 145, 146,
	143, 144, 141, 142, 139, 140, 57, 102, 138, 57,
	61, 97, 58, 27, 113, 109, 26, 25, 70, 63,
	24, 70, 23, 22, 136, 63, 56, 21, 123, 133,
	20, 63, 19, 18, 17, 95, 124, 16, 15, 14,
	13, 12, 134, 11, 99, 10, 1, 91, 119, 135,
	88, 85, 130, 125, 129, 132, 127, 82, 79, 120,
	115, 122, 117, 76, 73, 110, 103, 112, 105, 100,
	98, 96, 9, 8, 7, 57, 6, 57, 5, 102,
	4, 161, 113, 70, 160, 70, 163, 63, 165, 164,
	162, 63, 158, 133, 123, 63, 3, 0, 0, 0,
	0, 0, 124, 159, 0, 0, 134, 0, 0, 0,
	0, 0, 0, 0, 0, 119, 0, 0, 157, 129,
	28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
	38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
	48, 49, 50, 51, 52, 53, 54, 55,
}

var wktPact = [...]int16{
	186, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	16, 27, 27, 16, 27, 27, 16, 27, 27, -16,
	11, -16, 7, -16, -2, 21, 27, 27, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 24, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 24, -1000, -1000, -1000,
	16, -1000, -1000, -1000, -1000, 48, -1000, -1000, 48, -1000,
	-1000, -16, -1000, -1000, -16, -1000, -1000, -16, -1000, -1000,
	-16, -1000, 186, -1000, -1000, -23, 45, -1000, 39, -1000,
	37, -1000, -1000, 35, -1000, -1000, -1000, -1000, -1000, -1000,
	33, -1000, -1000, -1000, -1000, 31, -1000, -1000, -1000, -1000,
	29, -1000, -1000, -1000, -1000, 26, -1000, -1000, -1000, -1000,
	17, -1000, -1000, -1000, -1000, -21, -1000, -1000, -1000, -1000,
	24, -1000, 16, -1000, 48, -1000, 48, -1000, -16, -1000,
	-16, -1000, -16, -1000, -16, -1000, 186, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000,
}

var wktPgo = [...]uint8{
	0, 1, 166, 150, 148, 146, 144, 143, 142, 36,
	21, 10, 141, 47, 85, 140, 6, 13, 19, 139,
	8, 5, 138, 137, 28, 7, 136, 135, 134, 133,
	132, 131, 2, 9, 130, 129, 128, 127, 126, 125,
	3, 4, 123, 122, 121, 120, 119, 117, 116, 115,
	113, 111, 110, 109, 108, 107, 104, 103, 102, 100,
	97, 93, 92, 90, 87, 86, 83, 0,
}

var wktR1 = [...]int8{
	0, 48, 1, 1, 1, 1, 1, 1, 1, 2,
	2, 2, 49, 49, 50, 51, 51, 51, 3, 3,
	3, 52, 52, 53, 54, 54, 54, 4, 4, 4,
	55, 55, 56, 57, 57, 57, 5, 5, 5, 5,
	58, 59, 59, 59, 6, 6, 6, 6, 60, 61,
	61, 61, 7, 7, 7, 7, 62, 63, 63, 63,
	8, 8, 8, 47, 46, 46, 64, 64, 65, 66,
	66, 66, 67, 44, 45, 43, 43, 42, 42, 40,
	41, 38, 38, 39, 39, 36, 37, 34, 34, 35,
	35, 32, 33, 30, 30, 31, 31, 28, 29, 26,
	26, 27, 27, 24, 25, 22, 22, 23, 23, 21,
	21, 20, 19, 19, 18, 17, 16, 15, 15, 14,
	13, 12, 12, 9, 10, 11,
}

var wktR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 2,
	2, 2, 1, 1, 1, 1, 1, 1, 2, 2,
	2, 1, 1, 1, 1, 1, 1, 2, 2, 2,
	1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
	1, 1, 1, 1, 2, 2, 2, 2, 1, 1,
	1, 1, 2, 2, 2, 2, 1, 1, 1, 1,
	2, 2, 2, 3, 3, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 3, 3, 1, 3, 1, 1,
	1, 1, 1, 1, 1, 3, 3, 3, 1, 3,
	1, 1, 1, 1, 1, 1, 1, 3, 3, 3,
	1, 3, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 3, 1, 1, 1, 3, 3, 1, 3,
	1, 2, 1, 1, 1, 1,
}

var wktChk = [...]int16{
	-1000, -48, -1, -2, -3, -4, -5, -6, -7, -8,
	-49, -50, -51, -52, -53, -54, -55, -56, -57, -58,
	-59, -60, -61, -62, -63, -64, -65, -66, 4, 5,
	6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 29, 30, 31, -14, -67, 34, -9,
	-11, 32, -10, -11, -17, -16, -67, -9, -10, -20,
	-67, -9, -10, -28, -9, -67, -29, -10, 34, -36,
	-9, -67, -37, -10, 34, -44, -9, -67, -45, -10,
	34, -47, 34, -9, -10, -13, -12, 33, -15, -13,
	-19, -18, -16, -26, -24, -22, -21, -9, -13, -14,
	-27, -25, -23, -21, -10, -34, -32, -30, -17, -9,
	-35, -33, -31, -17, -10, -42, -40, -38, -20, -9,
	-43, -41, -39, -20, -10, -46, -1, 35, 33, 35,
	36, 35, 36, 35, 36, 35, 36, 35, 36, 35,
	36, 35, 36, 35, 36, 35, 36, -13, -18, -24,
	-25, -32, -33, -40, -41, -1,
}

var wktDef = [...]int8{
	0, -2, 1, 2, 3, 4, 5, 6, 7, 8,
	0, 12, 13, 0, 21, 22, 0, 30, 31, 0,
	0, 0, 0, 0, 0, 0, 66, 67, 14, 15,
	16, 17, 23, 24, 25, 26, 32, 33, 34, 35,
	40, 41, 42, 43, 48, 49, 50, 51, 56, 57,
	58, 59, 68, 69, 70, 71, 9, 0, 72, 10,
	123, 125, 11, 124, 18, 115, 0, 19, 20, 27,
	0, 28, 29, 36, 38, 0, 37, 39, 0, 44,
	46, 0, 45, 47, 0, 52, 54, 0, 53, 55,
	0, 60, 0, 61, 62, 0, 120, 122, 0, 118,
	0, 113, 114, 0, 100, 103, 105, 106, 109, 110,
	0, 102, 104, 107, 108, 0, 88, 91, 93, 94,
	0, 90, 92, 95, 96, 0, 78, 79, 81, 82,
	0, 76, 80, 83, 84, 0, 65, 119, 121, 116,
	0, 111, 0, 97, 0, 98, 0, 85, 0, 86,
	0, 73, 0, 74, 0, 63, 0, 117, 112, 99,
	101, 87, 89, 77, 75, 64,
}

var wktTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	34, 35, 3, 3, 36,
}

var wktTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33,
}

var wktTok3 = [...]int8{
	0,
}

var wktErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	wktDebug        = 0
	wktErrorVerbose = true
)

type wktLexer interface {
	Lex(lval *wktSymType) int
	Error(s string)
}

type wktParser interface {
	Parse(wktLexer) int
	Lookahead() int
}

type wktParserImpl struct {
	lval  wktSymType
	stack [wktInitialStackSize]wktSymType
	char  int
}

func (p *wktParserImpl) Lookahead() int { _ = "STUB: not implemented"; return 0 }

func wktNewParser() wktParser { _ = "STUB: not implemented"; return *new(wktParser) }

const wktFlag = -1000

func wktTokname(c int) string { _ = "STUB: not implemented"; return "" }

func wktStatname(s int) string { _ = "STUB: not implemented"; return "" }

func wktErrorMessage(state, lookAhead int) string { _ = "STUB: not implemented"; return "" }

// To match Bison, suggest at most four expected tokens.

// Look for shiftable tokens.

// Look for tokens that we accept or reduce.

// If the default action is to accept or reduce, give up.

func wktlex1(lex wktLexer, lval *wktSymType) (char, token int) {
	_ = "STUB: not implemented"
	return 0, 0
}

/* unknown char */

func wktParse(wktlex wktLexer) int { _ = "STUB: not implemented"; return 0 }

func (wktrcvr *wktParserImpl) Parse(wktlex wktLexer) int { _ = "STUB: not implemented"; return 0 }

// silence set and not used

/* number of errors */
/* error recovery flag */

// wktrcvr.char translated into internal numbering

// Make sure we report no lookahead when not parsing.

/* put a state and value onto the stack */

/* simple state */

/* valid shift */

/* default state action */

/* look through exception table */

/* error ... attempt to resume parsing */

/* brand new error */

/* incompletely recovered error ... try again */

/* find a state where "error" is a legal shift action */

/* simulate a shift of "error" */

/* the current p has no shift on "error", pop stack */

/* there is no state on the stack with an error shift ... abort */

/* no shift yet; clobber input char */

/* try again in the same state */

/* reduction by production wktn */

// guard against "declared and not used"

// wktp is now the index of $0. Perform the default action. Iff the
// reduced production is ε, $1 is possibly out of range.

/* consult goto table to find next state */

// dummy call; replaced with literal code

/* stack new state and value */
